### ISSUE TITLE
Missing class call in example files

### ISSUE THREAD

**Issue by b-lampe** [sandialabs/sansmic#41]
**Summary**
The first line of Cell 17 (or line 55) of the example file "basic.ipynb" omits calling the "model" class. Should be modified to:

test2scen = sansmic.model.Scenario(

The same omission happens multiple times in the example file.

Thanks!

![Screenshot 2024-10-02 151903](https://github.com/user-attachments/assets/b1158277-fac2-4c3e-b559-41504b174c04)

**Comment by dbhart** [comment]
I think we had originally promoted the Scenario class to the top level and then decided not to do that but forgot to update the examples. We need to get the examples pynb tests going so we catch this. 

Thank you @b-lampe for finding and reporting it! You get the 🥇 issue claim!

**Comment by dbhart** [comment]
Tests are passing, waiting on review at which point will merge in. See https://github.com/sandialabs/sansmic/actions/runs/11152706061
for output from the tests in the summary.
